version: '3'
services:
  jenkins:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .
    #image: jenkins:jcasc
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      sonarcreds: ${SONARCREDS}
      githubCodeRepoCredentials: ${GITHUBCODEREPOCREDENTIALS}
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      COMMERCE_CLOUD_USER= ${COMMERCE_CLOUD_USER}
      COMMERCE_CLOUD_PASSWORD= ${COMMERCE_CLOUD_PASSWORD}
  postgres:
    image: postgres:9.6
    networks:
      - jenkins
    environment:
      POSTGRES_USER: ${POSTGRES_SONAR_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SONAR_PASSWORD}
    volumes:
      - /var/postgres-data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
    environment:
      SONARQUBE_JDBC_USERNAME: ${POSTGRES_SONAR_USER}
      SONARQUBE_JDBC_PASSWORD: ${POSTGRES_SONAR_PASSWORD}
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres

networks:
  jenkins:
